language: python
python:
  - "3.6"
  - "3.7-dev"

# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install coveralls pytest-cov

# command to run tests
script:
  - py.test --cov=cihpc tests/

after_success:
  - coveralls

deploy:
  on:
    all_branches: true
  provider: pypi
  user: janhybs
  password:
    secure: a20amCl0pXJP1UpMR6JV0p0Rg/Nk6T/LbIuZbjjeMEFBtnQGCDgYcfJ1pj2loqp6OJ3VnVXcAEqVK3NaWKD1Rbe/UBzDGXH85U1xXanijYX+KA+6AbefSTOVZuKvhcwfpY5lNWk2daCfbJO02jqgWDEz7RPVcRYGErlGwEbz9ystach70gCajeaGiy0L+ebPQqdBSZ15B2RGF0YgDwSET4OfGG972BqLxqU0211KtshWoSnRmgRY7thuIteuNXNphaoSglAkFl0zI+QDUSbzYAl67AqFmATlDUSxCbyrFK0IalROuwxO40GlVjQtSs9FG2T9U0+Pn64StEQLO17GZk+ui8igg2XjZJ3+D+BXMJL5lAOB0ubf7JNT+vVXUKGbn86/mkKAx72WmGpphgYzN1sEVNRpI1XsFcxnAM08n3Us1KnNzM1m1SKImiZIpkaLKY7zFlEPcVtkySAxz74CGuiWU7oq98l7gfZP5tAVDXbMW4AL1pvcGJsIzcnO+jey0TyU5caVOD7WCjT31uo9r6YrNl023bZjOm5emDoiVxQmbPhO3QYAwx9KSeiOMqPeClu0p/J5fBJIwc9ghmLSlh6SdFw889Ggq9cZcsgMAXTu+1D6VOKeTBzT1e6y6dc8H6u82SQQi8HwZv0ipGdGTnneE1ZUAv/vCfEIlepC50o=
