workdir: <hello-world-workdir>
init-shell: !sh sh/init.sh
  
install:
  - name: compilation-phase
    output: stdout
    git:
    - url: https://github.com/janhybs/bench-stat.git
      commit: <arg.commit.hello-world> # checkout to this commit
      branch: <arg.branch.hello-world> # under this branch's name
      
    shell: !sh sh/install.sh

test:
  - name: memory-cache-test
    output: 'null'
    repeat:
      exactly: 20
      no-less-than: 20
      
    parallel:
      cpus: 0.51
      prop: <test.cpu>
      
    variables:
      - matrix:
        - test:
            - id: 1
              name: memory-cache-test-l1
            - id: 2
              name: memory-cache-test-l2
            - id: 3
              name: memory-cache-test-l3
      - matrix:
        - test:
            - id: 0
              name: memory-cache-test-all
            
    shell: !sh sh/test.sh
      
    collect:
      repo: bench-stat
      files: bench-stat/arts/<__unique__>/result-*.json
      module: artifacts.collect.modules.generic_module
      move-to: bench-stat/artifacts/<__project__.start.datetime>
      cut-prefix: null
      save-to-db: true
      extra:
        parallel:   15
        metric:     foobar      # additional property of the test you want to save
        test-id:    <test.id|i> # accessing current test
        test-name:  <test.name> # accessing current build matric data
